data:
  height: 256
  root: /root/autodl-tmp/bpbreid/Market-1501-v15.09.15
  sources: [market1501]
  targets: [market1501]
  transforms: [rc, re]
  width: 256
inference: {dataset_folder: data/datasets/bpbreid_dajixiang/crops_202603, dataset_name: dajixiang,
  enabled: true, gallery_features_path: '', load_gallery_features: false, num_classes: 21,
  output_folder: '', save_features: false}
model:
  bpbreid:
    backbone: hrnet32
    learnable_attention_enabled: true
    mask_filtering_testing: true
    mask_filtering_training: false
    masks: {dir: pifpaf_maskrcnn_filtering, preprocess: five_v}
    test_embeddings: [bn_foreg, parts]
  load_config: true
  load_weights: /root/autodl-tmp/MOT_WITH_PMMM/bpbreid/logs/DaJixiang_camera001_train/2026_02_06_17_13_31_13Sc86e5d82-b9df-4d9c-93cf-2601c760355dmodel/job-562693701_60_model.pth.tar
  name: bpbreid
