data:
  root: '/root/autodl-tmp/bpbreid/Market-1501-v15.09.15'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  transforms: ['rc', 're']

model:
  name: 'bpbreid'
  load_weights: '/root/autodl-tmp/bpbreid/torchreid/logs/560656311/2025_02_20_11_57/job-560656311_60_model.pth.tar'
  load_config: True
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'hrnet32'
    test_embeddings: ['bn_foreg', 'parts']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'five_v'

test:
  evaluate: True
  load_features: True
  gallery_features_path: '/root/autodl-tmp/bpbreid/torchreid/logs/462980077/features/gallery_features_market1501.pt'
  batch_size: 64
  visrank: True
